---
fixtures:
  repositories:
          "concat":
                  repo:  "https://github.com/puppetlabs/puppetlabs-concat.git"
          "stdlib":
                  repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
          "approx": "#{source_dir}"
